// src/hooks/index.js
export { useAuth, usePermissions } from './useAuth'
export { useLoading } from './useLoading'
export { useForm } from './useForm'
export { useLocalStorage } from './useLocalStorage'
export { useApi } from './useApi'
export { useDebounce, useDebouncedCallback } from './useDebounce'
export { useConfirmation } from './useConfirmation'
export { useNotification } from './useNotification'
export { usePagination } from './usePagination'
