version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - cd impocomgua-front
      - npm install

  build:
    commands:
      - npm run build

artifacts:
  base-directory: impocomgua-front/dist
  files:
    - '**/*'
