version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Instalando dependencias..."
      - pip install --upgrade pip
      - pip install -r requirements.txt

  pre_build:
    commands:
      - echo "Verificando estructura del backend"
      - ls -la
      - echo "Ejecutando pruebas"
      - pytest test || echo "Algunas pruebas fallaron, continuar de todos modos"

  build:
    commands:
      - echo "Build completado para el backend"

artifacts:
  files:
    - '**/*'
  base-directory: backend
